=== IBM/cp4mcm-samples/logs_data_checker/resources/log_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "",
  "title": "Normalized Log",
  "description": "A normalized log",
  "type": "object",
  "properties": {
    "application_group_id": {
      "description": "Unique identifier for the tenant which owns the application being monitored (defined by Watson IT)",
      "type": "string"
    },
    "application_id": {
      "description": "Unique identifier of the application being monitored (defined by Watson IT)",
      "type": "string"
    },
    "level": {
      "description": "Severity level from 1-5",
      "type": "integer"
    },
    "type": {
      "description": "Log type (e.g. StandardLog)",
      "type": "string"
    },
    "message": {
      "description": "The log message",
      "type": "string"
    },
    "instance_id": {
      "description": "Name of the log's application or instance",
      "type": "string"
    },
    "timestamp": {
      "description": "Millisecond timestamp of the log",
      "type": "integer"
    },
    "utc_timestamp": {
      "description": "UTC timestamp of the log",
      "type": "string"
    },
    "features": {
      "description": "empty array for log features",
      "type": "array"
    },
    "meta_features": {
      "description": "Empty array for meta features, such as time window",
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "entities": {
      "description": "JSON object of log's entities (pod, container, etc.)",
      "type": "object"
    }
  },
  "required": ["application_group_id", "application_id", "message", "instance_id", "timestamp", "features", "meta_features", "entities"]
}

=== IBM/cp4mcm-samples/logs_data_checker_tests/data/test_line.json
{
  "message": "invoking [applyModel] WorkspaceId = 1b69b204-5432-496f-8e61-da7e4b037730",
  "timestamp": 1578669135680,
  "instance_id": "nlu",
  "features": [],
  "meta_features": [
    {
      "type": "WindowMeta",
      "obj_value": {
        "start": 1578669130000,
        "end": 1578669140000
      }
    }
  ],
  "level": 1,
  "type": "StandardLog",
  "utc_timestamp": "2020-01-10 15:12:15.680000",
  "entities": {
    "pod": "pmp015-nlu-6bc9cb9574-pgkgg",
    "_cluster": "ld60",
    "container": "nlu"
  },
  "application_group_id": "1",
  "application_id": "1"
}

=== IBM/cp4mcm-samples/logs_data_checker_tests/data/normalized_example.json
{"message":"invoking [applyModel] WorkspaceId = 1b69b204-5432-496f-8e61-da7e4b037730","timestamp":1578669135680,"instance_id":"nlu","features":[],"meta_features":[{"type":"WindowMeta","obj_value":{"start":1578669130000,"end":1578669140000}}],"entities":{"pod":"pmp015-nlu-6bc9cb9574-pgkgg","_cluster":"ld60","container":"nlu"},"application_group_id":"1","application_id":"1"}

=== IBM/cp4mcm-samples/aiops-log-data-quality-checker/logs_data_checker_tests/data/test_line.json
{
  "message": "some logs",
  "timestamp": 1578669135680,
  "instance_id": "myapp",
  "features": [],
  "meta_features": [
    {
      "type": "WindowMeta",
      "obj_value": {
        "start": 1578669130000,
        "end": 1578669140000
      }
    }
  ],
  "level": 1,
  "type": "StandardLog",
  "utc_timestamp": "2020-01-10 15:12:15.680000",
  "entities": {
    "pod": "pod1",
    "_cluster": "cluster1",
    "container": "myapp"
  },
  "application_group_id": "1",
  "application_id": "1"
}

=== IBM/cp4mcm-samples/aiops-log-data-quality-checker/logs_data_checker_tests/data/normalized_example.json
{"message":"some message","timestamp":1578669135680,"instance_id":"myapp","features":[],"meta_features":[{"type":"WindowMeta","obj_value":{"start":1578669130000,"end":1578669140000}}],"entities":{"pod":"pod1","_cluster":"cluster1","container":"myapp"},"application_group_id":"1","application_id":"1"}
